[tox]
requires =
    tox>=4
    tox-uv>=1.13
env_list =
    py{311,312,313}
    formatter
    type
    coverage
skip_missing_interpreters = true

[testenv]
description = run the tests with pytest
runner = uv-venv-lock-runner
dependency_groups = dev, test, integration
extras = opcua, mqtt, http
commands = pytest {posargs:tests}

[testenv:type]
description = run type checks
runner = uv-venv-lock-runner
dependency_groups = dev, test, integration
extras = opcua, mqtt
commands = pyrefly check {posargs:machine_data_model tests}

[testenv:formatter]
description = run linter
runner = uv-venv-lock-runner
dependency_groups = dev
commands =
    ruff check --fix {posargs:machine_data_model tests}
    ruff format {posargs:machine_data_model tests}

[testenv:coverage]
description = run coverage report
runner = uv-venv-lock-runner
dependency_groups = dev, test, integration
commands = pytest --cov=machine_data_model --cov-report=term-missing {posargs:tests}
